version: "3.9"
networks:
  mlflow-network:

services:
  # mlflow-backend:
  #   container_name: mlflow-mysql
  #   image: mysql:8.0
  #   restart: always
  #   networks:
  #     - mlflow-network
  #   expose:
  #     - "3306"
  #   environment:
  #     - MYSQL_DATABASE=${MYSQL_DB_NAME}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - ./db/data:/var/lib/mysql:rw
  #     - ./db/my.cnf:/etc/mysql/conf.d/my.cnf:rw
  #     - ./db/sql:/docker-entrypoint-initdb.d:rw
  
  myqsl-adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - mlflow-network
    depends_on:
      # - mlflow-backend
      - cloudsql-proxy
    ports:
      - "${ADMINER_PORT}:8080"
  
  mlflow:
    container_name: mlflow
    build: ./mlflow
    image: mlflow
    restart: always
    depends_on: 
      # - mlflow-backend
      - cloudsql-proxy
    networks:
      - mlflow-network
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/dir/cred.json
    ports:
      - "${MLFLOW_PORT}:5000"
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@cloudsql-proxy:5433/${MYSQL_DB_NAME} --artifacts-destination ${GS_LOCATION} --default-artifact-root ${GS_LOCATION} --host 0.0.0.0
    volumes:
      - ./artifacts:/dir/artifacts:rw
    
  cloudsql-proxy:
      container_name: cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.11
      command: /cloud_sql_proxy --dir=/cloudsql -instances=tech-rnd-project:us-central1:mlflow-backend=tcp:0.0.0.0:5433 -credential_file=/secrets/cloudsql/credentials.json 
      ports:
        - 5433:5433
      volumes:
        - ./credentials.json:/secrets/cloudsql/credentials.json
      restart: always
      networks:
        - mlflow-network

# mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mlflow-backend:3306/${MYSQL_DB_NAME}